## Loading and preprocessing the data
activity_raw <- read.csv(unzip("activity.zip",exdir = "data"), header = TRUE)
activity <- na.omit(activity_raw)
str(activity)
summary(activity)
## Total number of steps taken per day
steps_per_day <- aggregate(activity$steps, by = list(Steps.Date = activity$date), FUN = "sum")
## Histogram for the total steps per day
hist(steps_per_day$x, col = "SteelBlue", 
     breaks = 25,
     main = "Total number of steps taken each day",
     xlab = "Number of steps per day")
## Additional details 
Details <- summary(steps_per_day)
print(Details)
## Average daily activity pattern
average_per_day <- aggregate(activity$steps, 
                             by = list(Interval = activity$interval), 
                             FUN = "mean")
## Type 1 Plot
plot(average_per_day$Interval, average_per_day$x, type = "l", 
     main = "Average daily activity pattern", 
     ylab = "Avarage number of steps taken", 
     xlab = "5-min intervals")
## Interval with the maximum number of steps
interval_row <- which.max(average_per_day$x)
max_interval <- average_per_day[interval_row,1]
print (max_interval)
## Imputing missing values
library(Hmisc)
activity_filled <- activity_raw
activity_filled$steps <- impute(activity_raw$steps, fun=mean)
## Total number of steps taken per day New
steps_per_day_new <- aggregate(activity_filled$steps, by = list(Steps.Date = activity_filled$date), FUN = "sum")
## Histogram for the total steps per day New
hist(steps_per_day_new$x, col = "SteelBlue", 
     breaks = 25,
     main = "Total number of steps taken each day New",
     xlab = "Number of steps per day")
## Additional details New
Details_new <- summary(steps_per_day_new)
print(Details_new)
## Average daily activity pattern New
average_per_day_new <- aggregate(activity_filled$steps, 
                                 by = list(Interval = activity_filled$interval), 
                                 FUN = "mean")
## Type 1 Plot New
plot(average_per_day_new$Interval, average_per_day_new$x, type = "l", 
     main = "Average daily activity pattern", 
     ylab = "Avarage number of steps taken", 
     xlab = "5-min intervals")
## Interval with the maximum number of steps
interval_row_new <- which.max(average_per_day_new$x)
max_interval_new <- average_per_day_new[interval_row,1]
print (max_interval_new)
## Differences in activity patterns between weekdays and weekends
activity_filled$date <- as.Date(activity_filled$date)
activity_filled$weekday <- weekdays(activity_filled$date)
activity_filled$day_type <- ifelse(activity_filled$weekday=="суббота" |
                                       activity_filled$weekday=="воскресенье","Weekend","Weekday")
activity_filled$day_type <- factor(activity_filled$day_type)
## number of steps for all 5-min intervals, averaged across weekdays and weekends
day_types_data <- aggregate(steps ~ interval + day_type, data=activity_filled, mean)

library(ggplot2)
ggplot(day_types_data, aes(interval, steps)) + 
    geom_line() + 
    facet_grid(day_type ~ .) +
    xlab("5-minute intervals") + 
    ylab("Avarage number of steps taken") +
    ggtitle("Weekdays and weekends activity patterns")